### ISSUE TITLE
Support veres one DID method

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#2]
See: https://github.com/digitalbazaar/bedrock-edv-storage/tree/support-did-v1

Roadmap:

* [x] Preliminary v1 testnet support
* [ ] Support the new `did-io`@v0.9 API - depends on [`did-veres-one`/#54](https://github.com/veres-one/did-veres-one/issues/54)
* [ ] Implement a documentLoader cache (to make this actually usable)

**Comment by mattcollier** [comment]
@dlongley is this totally complete?

**Comment by dlongley** [comment]
Not quite, only thing remaining is this FIXME though: https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L324-L328

And we'll need a v1 cache, but that's not specific to this module.

**Comment by mattcollier** [comment]
Waiting on https://github.com/digitalbazaar/did-io/pull/50

**Comment by dmitrizagidulin** [comment]
I updated the remaining steps in the description.

**Comment by dlongley** [comment]
Closed when https://github.com/digitalbazaar/did-io/pull/50 merged.
