### ISSUE TITLE
Potentially bad state with recreating deleted EDV documents

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#29]
There's a potential for bad updates to deleted EDV docs if we completely remove them instead of just tombstoning them. For example:

1. Client 1 created EDV Doc X, sequence = 0.
2. Client 2 reads EDV Doc X, sequence = 0.
3. Client 1 updates EDV Doc X, sequence = 1.
4. Client 3 reads EDV Doc X, sequence = 1.
5. Client 1 deletes EDV Doc X.
6. Client 4 (re)creates EDV Doc X, sequence = 0.
7. Client 2 updates EDV Doc X, sequence = 1.

At this point:

1. Client 2 successfully applies an update that should have failed.
2. Client 3 has a copy of X with sequence 1 that is different from Client 2's sequence 1 copy.
3. Maybe some other mayhem too, but already there's a clearly a state problem.

If EDV docs were instead tombstoned (i.e., leave a marker that a doc was deleted and do not allow it to be recreated), this could be avoided. The system could potentially even allow an update after deletion -- provided that the sequence number continues to increment. In short, the sequence number should monotonically increase.

**Comment by mattcollier** [comment]
@dlongley priority?
