### ISSUE TITLE
Add tests for sequence numbers between 2^32 and Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#30]
Tests should work with edv-client as well (and perhaps that repo needs similar tests?).

**Comment by aljones15** [comment]
I can take this if you want me to after I finish the validators.

**Comment by davidlehn** [comment]
Be sure to check every number in the range... just to be sure. :-)

**Comment by mattcollier** [comment]
Merged: https://github.com/digitalbazaar/bedrock-edv-storage/pull/31

**Comment by dlongley** [comment]
@mattcollier -- I don't see that the tests are working with edv-client. Feel free to close if that's not the case and we're covered there.

**Comment by mattcollier** [comment]
@dlongley you are correct, sorry.  Created new issue for those additional tests: https://github.com/digitalbazaar/bedrock-edv-storage/issues/33
