### ISSUE TITLE
Add tests for sequence numbers to HTTP API and edv-client

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-edv-storage#33]
New tests have recently been added to the Node.js API  for testing large sequence numbers.

We need to run those same test through the HTTP API by way of the edv-client.

Here are the Node.js tests: https://github.com/digitalbazaar/bedrock-edv-storage/blob/996fb4f36a53b78f3fb7492989c7361a153bc03c/test/mocha/12-insert.js#L50-L74

Here is a test spec that is setup to test the HTTP APIs using the edv-client libarary: 
https://github.com/digitalbazaar/bedrock-edv-storage/blob/996fb4f36a53b78f3fb7492989c7361a153bc03c/test/mocha/25-http-edv-client.js#L97-L98

**Comment by aljones15** [comment]
I am seeing the test that @davidlehn wrote in master:

```
nsert API
    ��� should insert a document
    ��� should insert a document with sequence number 0
    ��� should insert a document with sequence number 1
    ��� should insert a document with sequence number 2**31-1
    ��� should insert a document with sequence number 2**31
    ��� should insert a document with sequence number 2**31+1
    ��� should insert a document with sequence number 2**32-1
    ��� should insert a document with sequence number 2**32
    ��� should insert a document with sequence number 2**32+1 (46ms)
    ��� should insert a document with sequence number in range [2**32, MAX_SAFE_INTEGER] (middle)
    ��� should insert a document with sequence number in range [2**32, MAX_SAFE_INTEGER] (random)
    ��� should insert a document with sequence number MAX_SAFE_INTEGER-1
    ��� should insert a document with sequence number MAX_SAFE_INTEGER
    ��� should fail to insert a document with a negative sequence number
```

so I am assuming this can be closed.
