### ISSUE TITLE
Support a new option in the data passed to `find` to specify that only a count is desired

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#34]
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L326

If `count: true` is set in the request, only return back a count of the documents that match the query, not the document contents.

**Comment by mattcollier** [comment]
@dlongley the solution you're looking for here involves sidestepping as much crypto as possible right?  In order for the search to work, indexed fields will need to be hashed etc, but we don't want to decrypt all the fields once the document(s) are found.  Is this about right?

**Comment by mattcollier** [comment]
This is connected with this client issue: https://github.com/digitalbazaar/edv-client/issues/50

**Comment by dlongley** [comment]
@mattcollier,

> In order for the search to work, indexed fields will need to be hashed etc, but we don't want to decrypt all the fields once the document(s) are found. Is this about right?

Yeah, we don't want to decrypt anything, just find the docs that match the query and return the number. Btw, this is for the server portion of this feature and the server can't decrypt the docs anyway.

**Comment by aljones15** [comment]
@mattcollier @dlongley just to make sure (before I go any further on this)

1. use existing mongo count functionality: https://docs.mongodb.com/manual/reference/method/db.collection.count/
2. add a new method to `storage.count`
3. in the http api return `{count: number}` instead of results

**Comment by dlongley** [comment]
That sounds rightish. Any minor tweaks that might arise we can sort out once we have a concrete PR.

**Comment by aljones15** [comment]
this PR has been merged with test project into master so I am closing this as the count api has been implemented now.
