### ISSUE TITLE
When returning results from a query, return an object with the array of results in it

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#39]
We're presenting returning query results (encrypted documents) directly as a JSON array which does not allow us to be agile with future changes for pagination or other features. We should change the response from an array to an object with: `{documents: [/*the documents*/]}`. Bikeshedding on using the name `documents` welcome.

@mattcollier -- only tagging you here to get your opinions, not for implementation.

**Comment by mattcollier** [comment]
The term `doc` and `document` is used throught the `edv-client` library.  So either `docs` or `documents` would be fine with me.

**Comment by mattcollier** [comment]
Making this a P1 so we can get this rolling sooner rather than later and it will impact multiple modules.

**Comment by mattcollier** [comment]
@JSAssassin this pertains to the return value here:
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L369

We need to await the result there and wrap it in an object
```
const documents = await database.collections ...  .toArray();
return {document};
```

then you'll need to update the edv-client API corresponding to this request.  I think you recently did a similar set of PRs.
