### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#4]
Tests are no longer passing due to refactoring and so they need updating.

**Comment by aljones15** [comment]
is this still waiting?

**Comment by OR13** [comment]
yes

**Comment by mattcollier** [comment]
0 out of 42 test passing.  I am going to address this before any additional changes are made.

**Comment by aljones15** [comment]
@mattcollier I added myself to this issue just in case you have any issues / probably a good idea to follow this.

**Comment by aljones15** [comment]
Just a quick update here master is still failing however revocation:

  31 passing (2s)
  7 pending

so we have 7 tests that need to be revised.

**Comment by aljones15** [comment]
@mattcollier I'm adding this here so we can finalize what I need to do:

1. Add a revocation test similar to the one in http-kms
  - Create 3 keys, Alice, Bob, and Carol
  - Alice delegates write capabilities to Bob (with Bob as a delegator)
  - Bob in turn delegates his write capability to Carol.
  - Test that all 3 users can write to the same EDV.
  - Bob revoke's Carol's capability
  - Test that Alice and Bob can still write and Carol can not
  - Alice revoke's Bob's key
  - Verify that only Alice can write to the EDV

Should I also try to fix the remaining 7 tests being skipped?

**Comment by mattcollier** [comment]
The flow you've described sounds good to me.  I don't know what's going on with the skipped tests, put that aside for now.

**Comment by aljones15** [comment]
@mattcollier can this be closed?

**Comment by mattcollier** [comment]
Looks like test suite is operational now.  Closing.
