### ISSUE TITLE
Add validators to unvalidated Endpoints

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-edv-storage#40]
Routes:

- [ ] **app.get routes.edvs needs a query validator for controller & referenceId**
- [ ] **app.post routes.query needs a validator, but the one in `schemas` will need to be checked first**
- [ ] **app.post routes.authorizations needs a validator for a capability**
  - [ ] you will need to create a new validator for a zcap here
  - [ ] please note: we do need a zcap validator for more than just this library
- [ ] **app.get routes.authorizations uses req.params which we usually do not validate, but it also uses req.query which we do validate on.**
- [ ] **app.delete routes.authorizations uses req.params, but also needs the same validator that that the get route has req.query.id**
- [ ] app.get routes.edv does not need a validator (uses req.params)
- [ ] app.get routes.zcaps does not need a validator
- [ ] app.get routes.document does not need a validator (uses req.params)
- [ ] app.delete routes.document does not need a validator (uses req.params)
- [ ] app.get routes.chunk only uses req.params so probably does not need one
- [ ] app.delete routes.chunk only uses req.params so probably does not need one

none of the revocation endpoints have validators either

- [ ] app.post routes.revocations add a validator for a capability
  - this probably can be the same as the one for authorizations

**Comment by mattcollier** [comment]
@aljones15 thanks for putting together this checklist.  Unless you are actively working on it, please remove your name and in that case we'll queue it up for someone else to work on.

**Comment by aljones15** [comment]
@mattcollier I went ahead and removed myself from the assignees. Feel free to re-assign.

**Comment by aljones15** [comment]
Please only add validators for this task. Do not remove any existing ones.

**Comment by JSAssassin** [comment]
This is currently blocked by #57
Some work has been done on  https://github.com/digitalbazaar/bedrock-edv-storage/tree/add-validators.
(Note: the z-cap schema may need to be updated to a canonical schema later on.)
