### ISSUE TITLE
Remove checking zcap storage for authorizations

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#58]
We used to reference zcaps in http headers when invoking them -- rather than including them in full -- and this meant hitting the database to lookup a zcap by its ID. I believe we no longer need to support this so we should remove the code that is doing it because it creates unnecessary database hits. We do this in at least three places:

https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L215
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L259
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L359

```js
    // see if zcap is in storage
    try {
      const {authorization} = await brZCapStorage.authorizations.get(
        {id: url, invocationTarget});
      return {
        contextUrl: null,
        documentUrl: url,
        document: authorization.capability
      };
    } catch(e) {
      if(e.name !== 'NotFoundError') {
        throw e;
      }
    }
```

We should remove these instances (and any others) and ensure that our applications still function properly after doing so.

**Comment by mattcollier** [comment]
@dlongley you finding this sort of thing gives me a thought I didn't have before regarding KMS/edv performance, which is that it may have something to do with lock contention for records that are being used concurrently.  Just wanted to jot that down.

**Comment by dlongley** [comment]
We should make sure to do this before releasing 5.x. PR #65 has other changes for 5.x -- we need to remember to address this other issue when that PR gets merged and not publish without this.

**Comment by llorllale** [comment]
@dlongley is the path forward then to include them in full?

**Comment by dlongley** [comment]
@llorllale,

> is the path forward then to include them in full?

Yes. And our edv-client implementation has been sending the full chain for quite some time now.

**Comment by dlongley** [comment]
We should also remove the HTTP endpoints for adding authorizations as those are no longer needed either.

**Comment by mattcollier** [comment]
@dlongley wrt to removing authorizations endpoint, it is used during this flow in a test:

https://github.com/digitalbazaar/bedrock-edv-storage/blob/6647c75cdc5f927d59f9cb42f12ef6bca53caa7b/test/mocha/25-http-edv-client.js#L909-L971

**Comment by llorllale** [comment]
I am also curious as to what the strategy will be for a vault controller to authorize third party access.

**Comment by dlongley** [comment]
The authorizations endpoint has now been removed. When invoking a zcap, the entire zcap chain must be included. Full decentralized delegation is now supported.
