### ISSUE TITLE
Prevent removal of recipients w/o special privileges

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#6]
When writing documents, prevent recipients from being removed from previous docs unless authority is granted to do so. This may need to be implemented via caveats.

**Comment by mattcollier** [comment]
@dlongley what's the priority and latest thinking on this?

**Comment by dlongley** [comment]
The latest thinking is that a rudimentary version of this would be to require that any KEKs specified in the EDV config must always be present, otherwise a doc will be rejected. That should be implemented and the caveat stuff ignored for now.

**Comment by mandyvenables** [comment]
@dlongley I'm having trouble creating a test case that demonstrates this issue. Could you provide an example of a flow that illustrates this issue?

**Comment by dlongley** [comment]
The flow would involve giving someone a zcap to write to a document -- with an expectation that particular recipient(s) would be included -- and that person tries to write to the document and does not include those recipients. We haven't decided how to express this requirement yet which means we also don't know how to enforce it. I recommend we address other Priority 1 items before we get to this one.

**Comment by dlongley** [comment]
Deferring to priority 2 to enable trusted deployments until this can be remedied.

**Comment by dlongley** [comment]
The thinking here has changed to make it such that the recipients list will have just one recipient and it must always be present and match the KAK listed in the config in the EDV -- otherwise a posted encrypted doc or chunk should be rejected.

**Comment by dlongley** [comment]
Closing as invalid now -- there will be just one recipient.
