### ISSUE TITLE
Undefined remove method

### ISSUE THREAD

**Issue by tolson4** [digitalbazaar/bedrock-edv-storage#66]
There is a call to an undefined method `remove` in `https.js`.

https://github.com/digitalbazaar/bedrock-edv-storage/blob/9e40f0cfea6aae6edc8ece7cdf1f485636787e11/lib/http.js#L441

This appears to be a typo as the correct method in `storage.js` is named `removeChunk`
https://github.com/digitalbazaar/bedrock-edv-storage/blob/9e40f0cfea6aae6edc8ece7cdf1f485636787e11/lib/storage.js#L580-L590

Along with this, a unit test for document chunk deletion should be added.

**Comment by mattcollier** [comment]
@tolson4 Confirmed. Thank you for pointing this out.  We'll get a patch release put together soon.

**Comment by mattcollier** [comment]
@tolson4 there's a branch/PR for this fix https://github.com/digitalbazaar/bedrock-edv-storage/pull/67

We are already in-process for improving test coverage from this entire module.  I won't be able to include test coverage with this patch.
