### ISSUE TITLE
Add tests for streams/chunks to edv-storage

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-edv-storage#68]
We have front end tests for the chunks here:
https://github.com/digitalbazaar/edv-client/blob/master/tests/30-EdvStreams.spec.js

We have edv client tests in edv-storage here:
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/25-http-edv-client.js
https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/27-http-edv-client-update.js

none of the tests in edv-storage work on streams so we need to port the tests from edv-client to edv-storage.

Extends:
https://github.com/digitalbazaar/bedrock-edv-storage/issues/66

**Comment by dlongley** [comment]
Backend chunk tests have been added, closing.
