### ISSUE TITLE
Update to latest version `did-method-key-js`

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-edv-storage#76]
This is blocking testing for keyType Ed25519VerificationKey2020 in bedrock-profile.

**Comment by dmitrizagidulin** [comment]
Ready to test with `"@digitalbazaar/did-method-key-js": "digitalbazaar/did-method-key-js#v1.x"` newest version. See PR https://github.com/digitalbazaar/did-method-key-js/pull/35 for instructions (the README and the tests).

**Comment by JSAssassin** [comment]
This has been addressed https://github.com/digitalbazaar/bedrock-edv-storage/pull/77. Closing.
