### ISSUE TITLE
Add option to control JSON body parser limit for chunks based on `chunkSize`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-edv-storage#8]

**Comment by mattcollier** [comment]
@dlongley more detail here please.

**Comment by dlongley** [comment]
The JSON body parser is currently set on a *per server* basis to some value vs. allowing individual endpoints to decide what should be acceptable. For example, if it defaults to 100kb and chunk size is 1mb -- chunks will be rejected erroneously. We don't want to accept 1mb on every endpoint on the server, but it's acceptable for the chunk endpoint.

Having a small default enables us to block bad requests on most endpoints -- but we want to enable a larger payload on particular endpoints where other security measures can be put in place (e.g., rate limiting that may not be appropriate for other endpoints where smaller JSON body parser limits are appropriate) to prevent attacks.

**Comment by dlongley** [comment]
There's not a significant advantage to restricting this on different endpoints -- the attacker would just target the endpoints where it isn't restricted. Closing.
